# Generated by Django 5.2.7 on 2025-11-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_foodorder_check_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt_number', models.CharField(max_length=100)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='site_name',
            field=models.CharField(default='EpicTrail Adventures', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='support_email',
            field=models.EmailField(default='support@epictrail.co.ke', max_length=254),
        ),
    ]
