# Generated by Django 5.2.7 on 2025-11-19 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_rename_created_at_activity_activity_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Model Structure',
                'verbose_name_plural': 'Model Structures',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='foodOrder_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking', 'Booking'), ('registration', 'Registration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_activities',
            field=models.ManyToManyField(related_name='package_activities', to='myApp.activity'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomType_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomType_total_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
